In [21]:
import cv2
from matplotlib import pyplot as plt
import numpy as np

img = cv2.imread("opencv.png")
print(img)

# IMREAD_COLOR = 1
# IMREAD_UNCHANGED = -1

cv2.imshow("gopi",img)
cv2.waitKey(0)
# cv2.destroyAllWindows()

# plt.imshow(img, interpolation = 'bicubic')
# plt.plot([500,1000],[80,800], 'c', linewidth = 5)
# plt.show()

[[[ 70  56  41]
  [ 71  58  43]
  [ 68  57  42]
  ...
  [ 69  54  37]
  [ 75  57  35]
  [ 73  55  32]]

 [[192 177 162]
  [186 174 158]
  [185 176 161]
  ...
  [189 174 161]
  [192 174 155]
  [192 174 154]]

 [[195 179 163]
  [190 178 162]
  [141 134 119]
  ...
  [170 155 150]
  [195 178 163]
  [194 175 160]]

 ...

 [[170 147 126]
  [170 147 126]
  [170 147 126]
  ...
  [169 154 141]
  [185 180 164]
  [109 104  88]]

 [[170 147 126]
  [170 147 126]
  [170 147 126]
  ...
  [185 171 158]
  [183 178 162]
  [113 108  92]]

 [[170 147 126]
  [170 147 126]
  [170 147 126]
  ...
  [133 118 105]
  [132 126 111]
  [ 92  87  71]]]


-1

In [1]:
import cv2
import numpy as np

cap = cv2.VideoCapture(1)

while True:
    rat, frame = cap.read()
    cv2.imshow('frame',frame)
    
    if cv2.waitkey(1) and OxFF == ord('q'):
        break
        
# cap.release()
# cv2.destroyAllWindows()

error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-u4kjpz2z\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
